name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./miccore/
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack
